ServerEvents.tags('item', event => {
    // Weapons
	// To select weapons use '#www' in JEI 
    event.add('yyitems:www', 'aiotbotania:livingrock_sword');
    event.add('yyitems:www', 'aiotbotania:livingwood_sword');
    event.add('yyitems:www', 'alexsmobs:skelewag_sword');
    event.add('yyitems:www', 'alexsmobs:skelewag_sword_hand');
    event.add('yyitems:www', 'alexsmobs:skelewag_sword_inventory');
    event.add('yyitems:www', 'aquaculture:neptunium_bow');
    event.add('yyitems:www', 'aquaculture:neptunium_sword');
    event.add('yyitems:www', 'aquaculture:rainbow_trout');
    event.add('yyitems:www', 'aquamirae:dagger_of_greed');
    event.add('yyitems:www', 'aquamirae:terrible_sword');
    event.add('yyitems:www', 'biomeswevegone:rainbow_eucalyptus_bookshelf');
    event.add('yyitems:www', 'born_in_chaos_v1:bonescaller_staff');
    event.add('yyitems:www', 'born_in_chaos_v1:dark_ritual_dagger');
    event.add('yyitems:www', 'born_in_chaos_v1:intoxicating_dagger');
    event.add('yyitems:www', 'born_in_chaos_v1:spider_bite_sword');
    event.add('yyitems:www', 'born_in_chaos_v1:spiritual_sword');
    event.add('yyitems:www', 'born_in_chaos_v1:staff_of_magic_arrows');
    event.add('yyitems:www', 'born_in_chaos_v1:sweet_sword');
    event.add('yyitems:www', 'bosses_of_mass_destruction:earthdive_spear');
    event.add('yyitems:www', 'cgs:nailgun_splitter');
    event.add('yyitems:www', 'cgs:round_shotgun_blank');
    event.add('yyitems:www', 'cgs:shotgun_drum');
    event.add('yyitems:www', 'cgs:shotgun_pump');
    event.add('yyitems:www', 'constructionwand:core_angel');
    event.add('yyitems:www', 'constructionwand:core_destruction');
    event.add('yyitems:www', 'constructionwand:diamond_wand');
    event.add('yyitems:www', 'constructionwand:infinity_wand');
    event.add('yyitems:www', 'constructionwand:iron_wand');
    event.add('yyitems:www', 'constructionwand:stone_wand');
    event.add('yyitems:www', 'corn_delight:nachos_bowl');
    event.add('yyitems:www', 'create:wand_of_symmetry');
    event.add('yyitems:www', 'create_sa:brass_sword');
    event.add('yyitems:www', 'create_sa:experience_sword');
    event.add('yyitems:www', 'create_sa:rose_quartz_sword');
    event.add('yyitems:www', 'create_sa:zinc_sword');
    event.add('yyitems:www', 'createbigcannons:ap_autocannon_round');
    event.add('yyitems:www', 'createbigcannons:autocannon_ammo_container');
    event.add('yyitems:www', 'createbigcannons:autocannon_breech_cast_mould');
    event.add('yyitems:www', 'createbigcannons:autocannon_cartridge');
    event.add('yyitems:www', 'createbigcannons:autocannon_recoil_spring_cast_mould');
    event.add('yyitems:www', 'createbigcannons:built_up_nethersteel_cannon_chamber');
    event.add('yyitems:www', 'createbigcannons:built_up_steel_cannon_chamber');
    event.add('yyitems:www', 'createbigcannons:cannon_builder');
    event.add('yyitems:www', 'createbigcannons:cannon_carriage');
    event.add('yyitems:www', 'createbigcannons:cannon_crafting_wand');
    event.add('yyitems:www', 'createbigcannons:cannon_end_cast_mould');
    event.add('yyitems:www', 'createbigcannons:cannon_loader');
    event.add('yyitems:www', 'createbigcannons:cannon_mount');
    event.add('yyitems:www', 'createbigcannons:cannon_mount_extension');
    event.add('yyitems:www', 'createbigcannons:cannon_welder');
    event.add('yyitems:www', 'createbigcannons:cast_iron_autocannon_breech');
    event.add('yyitems:www', 'createbigcannons:cast_iron_autocannon_breech_extractor');
    event.add('yyitems:www', 'createbigcannons:cast_iron_autocannon_recoil_spring');
    event.add('yyitems:www', 'createbigcannons:cast_iron_cannon_chamber');
    event.add('yyitems:www', 'createbigcannons:cast_iron_cannon_end');
    event.add('yyitems:www', 'createbigcannons:creative_autocannon_ammo_container');
    event.add('yyitems:www', 'createbigcannons:empty_autocannon_cartridge');
    event.add('yyitems:www', 'createbigcannons:empty_machine_gun_round');
    event.add('yyitems:www', 'createbigcannons:filled_autocannon_cartridge');
    event.add('yyitems:www', 'createbigcannons:fixed_cannon_mount');
    event.add('yyitems:www', 'createbigcannons:flak_autocannon_round');
    event.add('yyitems:www', 'createbigcannons:large_nethersteel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:large_steel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:machine_gun_round');
    event.add('yyitems:www', 'createbigcannons:medium_nethersteel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:medium_steel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:nethersteel_cannon_chamber');
    event.add('yyitems:www', 'createbigcannons:packed_guncotton');
    event.add('yyitems:www', 'createbigcannons:packed_gunpowder');
    event.add('yyitems:www', 'createbigcannons:pair_of_cannon_wheels');
    event.add('yyitems:www', 'createbigcannons:partial_cast_iron_autocannon_breech_extractor');
    event.add('yyitems:www', 'createbigcannons:partial_steel_autocannon_breech_extractor');
    event.add('yyitems:www', 'createbigcannons:partially_assembled_machine_gun_round');
    event.add('yyitems:www', 'createbigcannons:partially_filled_autocannon_cartridge');
    event.add('yyitems:www', 'createbigcannons:partially_formed_autocannon_cartridge');
    event.add('yyitems:www', 'createbigcannons:small_nethersteel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:small_steel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:steel_autocannon_breech');
    event.add('yyitems:www', 'createbigcannons:steel_autocannon_breech_extractor');
    event.add('yyitems:www', 'createbigcannons:steel_autocannon_recoil_spring');
    event.add('yyitems:www', 'createbigcannons:steel_cannon_chamber');
    event.add('yyitems:www', 'createbigcannons:thick_nethersteel_cannon_chamber');
    event.add('yyitems:www', 'createbigcannons:thick_steel_cannon_chamber');
    event.add('yyitems:www', 'createbigcannons:very_large_nethersteel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:very_large_steel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:very_small_nethersteel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:very_small_steel_cannon_layer');
    event.add('yyitems:www', 'createbigcannons:wrought_iron_cannon_chamber');
    event.add('yyitems:www', 'createbigcannons:wrought_iron_cannon_end');
    event.add('yyitems:www', 'createfood:macaroni_bowl');
    event.add('yyitems:www', 'createfood:macaroni_bowl_bacon');
    event.add('yyitems:www', 'createfood:macaroni_bowl_cheese');
    event.add('yyitems:www', 'createfood:macaroni_bowl_cheese_bacon');
    event.add('yyitems:www', 'createfood:macaroni_bowl_cheese_sausage');
    event.add('yyitems:www', 'createfood:macaroni_bowl_sausage');
    event.add('yyitems:www', 'createfood:nacho_bowl');
    event.add('yyitems:www', 'createfood:tortilla_chip_bowl');
    event.add('yyitems:www', 'createmechanicalcompanion:mounted_crossbow');
    event.add('yyitems:www', 'cte2modpackarmors:desolating_light_staff');
    event.add('yyitems:www', 'cte2modpackarmors:lightning_edge_staff');
    event.add('yyitems:www', 'cte2modpackarmors:sinful_lights_staff');
    event.add('yyitems:www', 'cte2modpackarmors:soulcursed_skewer_dagger');
    event.add('yyitems:www', 'cte2modpackarmors:twin_agony_dagger');
    event.add('yyitems:www', 'cte2modpackarmors:unsealing_fate_sword');
    event.add('yyitems:www', 'deeperdarker:resonarium_sword');
    event.add('yyitems:www', 'deeperdarker:sonorous_staff');
    event.add('yyitems:www', 'deeperdarker:warden_sword');
    event.add('yyitems:www', 'doggytalents:food_bowl');
    event.add('yyitems:www', 'doggytalents:rice_bowl');
    event.add('yyitems:www', 'doggytalents:uncooked_rice_bowl');
    event.add('yyitems:www', 'endersdelight:shulker_bowl');
    event.add('yyitems:www', 'endersdelight:stuffed_shulker_bowl');
    event.add('yyitems:www', 'kobolds:kobold_iron_sword');
    event.add('yyitems:www', 'lightmanscurrency:auction_stand_biomeswevegone_rainbow_eucalyptus');
    event.add('yyitems:www', 'lightmanscurrency:card_display_biomeswevegone_rainbow_eucalyptus');
    event.add('yyitems:www', 'lightmanscurrency:variant_wand');
    event.add('yyitems:www', 'mca:staff_of_life');
    event.add('yyitems:www', 'minecraft:diamond_sword');
    event.add('yyitems:www', 'minecraft:golden_sword');
    event.add('yyitems:www', 'minecraft:iron_sword');
    event.add('yyitems:www', 'minecraft:netherite_sword');
    event.add('yyitems:www', 'minecraft:stone_sword');
    event.add('yyitems:www', 'minecraft:wooden_sword');
    event.add('yyitems:www', 'moresnifferflowers:wand_of_cubing');
    event.add('yyitems:www', 'mowziesmobs:naga_fang_dagger');
    event.add('yyitems:www', 'mowziesmobs:sculptor_staff');
    event.add('yyitems:www', 'outer_end:sinker_dagger');
    event.add('yyitems:www', 'outer_end:sinker_shuriken');
    event.add('yyitems:www', 'remnant_bosses:ossukage_sword');
    event.add('yyitems:www', 'roe_weapons:admin_bow');
    event.add('yyitems:www', 'roe_weapons:bow_0');
    event.add('yyitems:www', 'roe_weapons:bow_0_pulling_0');
    event.add('yyitems:www', 'roe_weapons:bow_0_pulling_1');
    event.add('yyitems:www', 'roe_weapons:bow_0_pulling_2');
    event.add('yyitems:www', 'roe_weapons:bow_1');
    event.add('yyitems:www', 'roe_weapons:bow_1_pulling_0');
    event.add('yyitems:www', 'roe_weapons:bow_1_pulling_1');
    event.add('yyitems:www', 'roe_weapons:bow_1_pulling_2');
    event.add('yyitems:www', 'roe_weapons:bow_2');
    event.add('yyitems:www', 'roe_weapons:bow_2_pulling_0');
    event.add('yyitems:www', 'roe_weapons:bow_2_pulling_1');
    event.add('yyitems:www', 'roe_weapons:bow_2_pulling_2');
    event.add('yyitems:www', 'roe_weapons:bow_3');
    event.add('yyitems:www', 'roe_weapons:bow_3_pulling_0');
    event.add('yyitems:www', 'roe_weapons:bow_3_pulling_1');
    event.add('yyitems:www', 'roe_weapons:bow_3_pulling_2');
    event.add('yyitems:www', 'roe_weapons:bow_4');
    event.add('yyitems:www', 'roe_weapons:bow_4_pulling_0');
    event.add('yyitems:www', 'roe_weapons:bow_4_pulling_1');
    event.add('yyitems:www', 'roe_weapons:bow_4_pulling_2');
    event.add('yyitems:www', 'roe_weapons:bow_5');
    event.add('yyitems:www', 'roe_weapons:bow_5_pulling_0');
    event.add('yyitems:www', 'roe_weapons:bow_5_pulling_1');
    event.add('yyitems:www', 'roe_weapons:bow_5_pulling_2');
    event.add('yyitems:www', 'roe_weapons:bow_6');
    event.add('yyitems:www', 'roe_weapons:bow_6_pulling_0');
    event.add('yyitems:www', 'roe_weapons:bow_6_pulling_1');
    event.add('yyitems:www', 'roe_weapons:bow_6_pulling_2');
    event.add('yyitems:www', 'roe_weapons:bow_7');
    event.add('yyitems:www', 'roe_weapons:bow_7_pulling_0');
    event.add('yyitems:www', 'roe_weapons:bow_7_pulling_1');
    event.add('yyitems:www', 'roe_weapons:bow_7_pulling_2');
    event.add('yyitems:www', 'roe_weapons:buckler_shield_0');
    event.add('yyitems:www', 'roe_weapons:buckler_shield_1');
    event.add('yyitems:www', 'roe_weapons:buckler_shield_2');
    event.add('yyitems:www', 'roe_weapons:buckler_shield_3');
    event.add('yyitems:www', 'roe_weapons:buckler_shield_4');
    event.add('yyitems:www', 'roe_weapons:buckler_shield_5');
    event.add('yyitems:www', 'roe_weapons:buckler_shield_6');
    event.add('yyitems:www', 'roe_weapons:buckler_shield_7');
    event.add('yyitems:www', 'roe_weapons:bustersword');
    event.add('yyitems:www', 'roe_weapons:crossbow_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_0_charged');
    event.add('yyitems:www', 'roe_weapons:crossbow_0_pulling_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_0_pulling_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_0_pulling_2');
    event.add('yyitems:www', 'roe_weapons:crossbow_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_1_charged');
    event.add('yyitems:www', 'roe_weapons:crossbow_1_pulling_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_1_pulling_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_1_pulling_2');
    event.add('yyitems:www', 'roe_weapons:crossbow_2');
    event.add('yyitems:www', 'roe_weapons:crossbow_2_charged');
    event.add('yyitems:www', 'roe_weapons:crossbow_2_pulling_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_2_pulling_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_2_pulling_2');
    event.add('yyitems:www', 'roe_weapons:crossbow_3');
    event.add('yyitems:www', 'roe_weapons:crossbow_3_charged');
    event.add('yyitems:www', 'roe_weapons:crossbow_3_pulling_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_3_pulling_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_3_pulling_2');
    event.add('yyitems:www', 'roe_weapons:crossbow_4');
    event.add('yyitems:www', 'roe_weapons:crossbow_4_charged');
    event.add('yyitems:www', 'roe_weapons:crossbow_4_pulling_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_4_pulling_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_4_pulling_2');
    event.add('yyitems:www', 'roe_weapons:crossbow_5');
    event.add('yyitems:www', 'roe_weapons:crossbow_5_charged');
    event.add('yyitems:www', 'roe_weapons:crossbow_5_pulling_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_5_pulling_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_5_pulling_2');
    event.add('yyitems:www', 'roe_weapons:crossbow_6');
    event.add('yyitems:www', 'roe_weapons:crossbow_6_charged');
    event.add('yyitems:www', 'roe_weapons:crossbow_6_pulling_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_6_pulling_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_6_pulling_2');
    event.add('yyitems:www', 'roe_weapons:crossbow_7');
    event.add('yyitems:www', 'roe_weapons:crossbow_7_charged');
    event.add('yyitems:www', 'roe_weapons:crossbow_7_pulling_0');
    event.add('yyitems:www', 'roe_weapons:crossbow_7_pulling_1');
    event.add('yyitems:www', 'roe_weapons:crossbow_7_pulling_2');
    event.add('yyitems:www', 'roe_weapons:cursed_bow');
    event.add('yyitems:www', 'roe_weapons:cursed_bow_pulling_0');
    event.add('yyitems:www', 'roe_weapons:cursed_bow_pulling_1');
    event.add('yyitems:www', 'roe_weapons:cursed_bow_pulling_2');
    event.add('yyitems:www', 'roe_weapons:cursed_dagger');
    event.add('yyitems:www', 'roe_weapons:cursed_gauntlet');
    event.add('yyitems:www', 'roe_weapons:cursed_greatsword');
    event.add('yyitems:www', 'roe_weapons:cursed_mace');
    event.add('yyitems:www', 'roe_weapons:cursed_shield');
    event.add('yyitems:www', 'roe_weapons:cursed_spear');
    event.add('yyitems:www', 'roe_weapons:cursed_staff');
    event.add('yyitems:www', 'roe_weapons:cursed_sword');
    event.add('yyitems:www', 'roe_weapons:dagger_0');
    event.add('yyitems:www', 'roe_weapons:dagger_1');
    event.add('yyitems:www', 'roe_weapons:dagger_2');
    event.add('yyitems:www', 'roe_weapons:dagger_3');
    event.add('yyitems:www', 'roe_weapons:dagger_4');
    event.add('yyitems:www', 'roe_weapons:dagger_5');
    event.add('yyitems:www', 'roe_weapons:dagger_6');
    event.add('yyitems:www', 'roe_weapons:dagger_7');
    event.add('yyitems:www', 'roe_weapons:dragon_slayer');
    event.add('yyitems:www', 'roe_weapons:featherdraw');
    event.add('yyitems:www', 'roe_weapons:gauntlet_0');
    event.add('yyitems:www', 'roe_weapons:gauntlet_1');
    event.add('yyitems:www', 'roe_weapons:gauntlet_2');
    event.add('yyitems:www', 'roe_weapons:gauntlet_3');
    event.add('yyitems:www', 'roe_weapons:gauntlet_4');
    event.add('yyitems:www', 'roe_weapons:gauntlet_5');
    event.add('yyitems:www', 'roe_weapons:gauntlet_6');
    event.add('yyitems:www', 'roe_weapons:gauntlet_7');
    event.add('yyitems:www', 'roe_weapons:greatsword_0');
    event.add('yyitems:www', 'roe_weapons:greatsword_1');
    event.add('yyitems:www', 'roe_weapons:greatsword_2');
    event.add('yyitems:www', 'roe_weapons:greatsword_3');
    event.add('yyitems:www', 'roe_weapons:greatsword_4');
    event.add('yyitems:www', 'roe_weapons:greatsword_5');
    event.add('yyitems:www', 'roe_weapons:greatsword_6');
    event.add('yyitems:www', 'roe_weapons:greatsword_7');
    event.add('yyitems:www', 'roe_weapons:katar');
    event.add('yyitems:www', 'roe_weapons:kunai_0');
    event.add('yyitems:www', 'roe_weapons:kunai_1');
    event.add('yyitems:www', 'roe_weapons:kunai_2');
    event.add('yyitems:www', 'roe_weapons:kunai_3');
    event.add('yyitems:www', 'roe_weapons:kunai_4');
    event.add('yyitems:www', 'roe_weapons:kunai_5');
    event.add('yyitems:www', 'roe_weapons:kunai_6');
    event.add('yyitems:www', 'roe_weapons:kunai_7');
    event.add('yyitems:www', 'roe_weapons:mace_0');
    event.add('yyitems:www', 'roe_weapons:mace_1');
    event.add('yyitems:www', 'roe_weapons:mace_2');
    event.add('yyitems:www', 'roe_weapons:mace_3');
    event.add('yyitems:www', 'roe_weapons:mace_4');
    event.add('yyitems:www', 'roe_weapons:mace_5');
    event.add('yyitems:www', 'roe_weapons:mace_6');
    event.add('yyitems:www', 'roe_weapons:mace_7');
    event.add('yyitems:www', 'roe_weapons:mastersword');
    event.add('yyitems:www', 'roe_weapons:orderofdespair');
    event.add('yyitems:www', 'roe_weapons:rapier_0');
    event.add('yyitems:www', 'roe_weapons:rapier_1');
    event.add('yyitems:www', 'roe_weapons:rapier_2');
    event.add('yyitems:www', 'roe_weapons:rapier_3');
    event.add('yyitems:www', 'roe_weapons:rapier_4');
    event.add('yyitems:www', 'roe_weapons:rapier_5');
    event.add('yyitems:www', 'roe_weapons:rapier_6');
    event.add('yyitems:www', 'roe_weapons:rapier_7');
    event.add('yyitems:www', 'roe_weapons:shield_0');
    event.add('yyitems:www', 'roe_weapons:shield_1');
    event.add('yyitems:www', 'roe_weapons:shield_2');
    event.add('yyitems:www', 'roe_weapons:shield_3');
    event.add('yyitems:www', 'roe_weapons:shield_4');
    event.add('yyitems:www', 'roe_weapons:shield_5');
    event.add('yyitems:www', 'roe_weapons:shield_6');
    event.add('yyitems:www', 'roe_weapons:shield_7');
    event.add('yyitems:www', 'roe_weapons:spear_0');
    event.add('yyitems:www', 'roe_weapons:spear_1');
    event.add('yyitems:www', 'roe_weapons:spear_2');
    event.add('yyitems:www', 'roe_weapons:spear_3');
    event.add('yyitems:www', 'roe_weapons:spear_4');
    event.add('yyitems:www', 'roe_weapons:spear_5');
    event.add('yyitems:www', 'roe_weapons:spear_6');
    event.add('yyitems:www', 'roe_weapons:spear_7');
    event.add('yyitems:www', 'roe_weapons:staff_0');
    event.add('yyitems:www', 'roe_weapons:staff_1');
    event.add('yyitems:www', 'roe_weapons:staff_2');
    event.add('yyitems:www', 'roe_weapons:staff_3');
    event.add('yyitems:www', 'roe_weapons:staff_4');
    event.add('yyitems:www', 'roe_weapons:staff_5');
    event.add('yyitems:www', 'roe_weapons:staff_6');
    event.add('yyitems:www', 'roe_weapons:staff_7');
    event.add('yyitems:www', 'roe_weapons:sword_0');
    event.add('yyitems:www', 'roe_weapons:sword_1');
    event.add('yyitems:www', 'roe_weapons:sword_2');
    event.add('yyitems:www', 'roe_weapons:sword_3');
    event.add('yyitems:www', 'roe_weapons:sword_4');
    event.add('yyitems:www', 'roe_weapons:sword_5');
    event.add('yyitems:www', 'roe_weapons:sword_6');
    event.add('yyitems:www', 'roe_weapons:sword_7');
    event.add('yyitems:www', 'roe_weapons:tome_0');
    event.add('yyitems:www', 'roe_weapons:tome_1');
    event.add('yyitems:www', 'roe_weapons:tome_2');
    event.add('yyitems:www', 'roe_weapons:tome_3');
    event.add('yyitems:www', 'roe_weapons:tome_4');
    event.add('yyitems:www', 'roe_weapons:tome_5');
    event.add('yyitems:www', 'roe_weapons:tome_6');
    event.add('yyitems:www', 'roe_weapons:tome_7');
    event.add('yyitems:www', 'roe_weapons:totem_0');
    event.add('yyitems:www', 'roe_weapons:totem_1');
    event.add('yyitems:www', 'roe_weapons:totem_2');
    event.add('yyitems:www', 'roe_weapons:totem_3');
    event.add('yyitems:www', 'roe_weapons:totem_4');
    event.add('yyitems:www', 'roe_weapons:totem_5');
    event.add('yyitems:www', 'roe_weapons:totem_6');
    event.add('yyitems:www', 'roe_weapons:totem_7');
    event.add('yyitems:www', 'roe_weapons:tower_shield_0');
    event.add('yyitems:www', 'roe_weapons:tower_shield_1');
    event.add('yyitems:www', 'roe_weapons:tower_shield_2');
    event.add('yyitems:www', 'roe_weapons:tower_shield_3');
    event.add('yyitems:www', 'roe_weapons:tower_shield_4');
    event.add('yyitems:www', 'roe_weapons:tower_shield_5');
    event.add('yyitems:www', 'roe_weapons:tower_shield_6');
    event.add('yyitems:www', 'roe_weapons:tower_shield_7');
    event.add('yyitems:www', 'roe_weapons:wirtsleg');
    event.add('yyitems:www', 'roe_weapons:wolf_claws');
    event.add('yyitems:www', 'seadwellers:depth_sword');
    event.add('yyitems:www', 'stalwart_dungeons:awful_dagger');
    event.add('yyitems:www', 'stalwart_dungeons:awful_gun');
    event.add('yyitems:www', 'stalwart_dungeons:cannon_pr');
    event.add('yyitems:www', 'stalwart_dungeons:chorundum_sword');
    event.add('yyitems:www', 'stalwart_dungeons:shulker_cannon_item');
    event.add('yyitems:www', 'stalwart_dungeons:tungsten_sword');
    event.add('yyitems:www', 'twilightforest:ender_bow');
    event.add('yyitems:www', 'twilightforest:fiery_sword');
    event.add('yyitems:www', 'twilightforest:giant_sword');
    event.add('yyitems:www', 'twilightforest:ice_bow');
    event.add('yyitems:www', 'twilightforest:ice_sword');
    event.add('yyitems:www', 'twilightforest:seeker_bow');
    event.add('yyitems:www', 'twilightforest:steeleaf_sword');
    event.add('yyitems:www', 'twilightforest:triple_bow');
    event.add('yyitems:www', 'undergarden:cloggrum_battleaxe');
    event.add('yyitems:www', 'undergarden:cloggrum_sword');
    event.add('yyitems:www', 'undergarden:forgotten_battleaxe');
    event.add('yyitems:www', 'undergarden:forgotten_sword');
    event.add('yyitems:www', 'undergarden:froststeel_sword');
    event.add('yyitems:www', 'undergarden:slop_bowl');
    event.add('yyitems:www', 'undergarden:utherium_sword');
    event.add('yyitems:www', 'undergardendelight:stuffed_gloomgourd_bowl');
});


/*
I've came up with an idea that it would be great to see only usefull items in JET.
...But what is useful? I think there should be some categories that I want to see.

Please help me populating this lists


ServerEvents.tags('item', event => {
    // All non decorative, create (and accompanied mods) here
    // Also should include all basic automation blocks from minecraft (piston, dispenset, etc)
    event.add('yyitems:ccc','create:gearshift');
    event.add('yyitems:ccc','create:encased_chain_drive');

    // All non decorative, 'mainline' botania blocks and items
    event.add('yyitems:bbb','botania:mana_pool');

    // All non redstone blocks should be here
    event.add('yyitems:rrr','minecraft:redstone');

    // Variations. All variations except for the wood or color variation of an item should have this tag.
    // This way one can use '-#vvv' in JEI to get rid of all variations in search result (while keeping the first one)
    event.add('yyitems:vvv', 'minecraft:spruce_log');

    // All foods and foods only. Not ingredients, not kitchen tools.
    event.add('yyitems:fff','minecraft:bread');

    // Armors
    //event.add('yyitems:aaa', 'minecraft:bread');

    // Weapons
    //event.add('yyitems:www', 'minecraft:bread');

    // Decoratives
    //event.add('yyitems:ddd', 'minecraft:bread');

});
// Other ids go here in comments, I'll decide what to do with them later.


// Get only ids that you find in my other script below, then put that ids to correct categories.
// If an item doesn't have any good category to go to - just skip it and put into list "others"
// Please note that you should use exactly this syntax event.add('tag', 'item_id'); - because kubejs doesn't support arrays in any of these parameters.
*/