
#Balanced Flight Settings
[Settings]

	[Settings."Flight Options"]
		"Ascended Ring Gives Unlimited Creative Flight (will fall back to Basic tier inside range)" = true
		"Ascended Ring Also Works As Elytra" = true
		"Flight Anchor Gives Creative Flight" = true
		"Flight Anchor Gives Elytra Flight" = false

	[Settings."Balancing Config"]
		#Range: 0.0 ~ 10.0
		"Anchor Distance Multiplier (0d -> 10d, default 1d)" = 1.0
		#Range: > 0
		"Anchor stress impact" = 256
		"Disable Fall Damage When Wearing Ascended Ring" = true
		"Disable Fall Damage Near Flight Anchor" = true
		"Enable Mining Speed Amplifier While Flying" = true
		#Range: 1 ~ 255
		"Mining Speed Amplifier While Flying (1 -> 255, default 25)" = 25

	[Settings."Enhanced Elytra Mechanics"]
		"Disable Elytra Damage" = true
		"Enable Elytra Flight From Ground" = true
		"Enable Take Off Mechanic" = true
		"Infinite Rockets" = true

	[Settings."Dimension Restrictions"]
		#Additional Allowed Dimensions for Flight (Only works in the Overworld by default)
		#Example of a valid list:
		#  ["minecraft:the_nether", "minecraft:the_end", "mymod:custom_dimension"]
		"Additional Allowed Dimensions for Flight" = []

