
[general]
	#Minimum number of pursuing mobs to trigger a music sequence
	#Range: > 1
	minPursuitEntities = 3
	#Seconds without mobs around needed for music to stop itself.
	#Range: > 1
	decayTime = 10
	#Resource locations of sounds to play. Separate with commas.
	sounds = ["minecraft:music_disc.pigstep", "minecraft:music_disc.mellohi", "minecraft:music_disc.cat", "minecraft:music_disc.mall", "minecraft:music_disc.otherside", "minecraft:music_disc.relic", "minecraft:music_disc.wait", "minecraft:music_disc.ward"]

