
#Backpack
[backpack]
	#Keep Backpack equipped in Curios slot upon death.
	keepBackpackOnDeath = true
	#Enable Jetpack boosting while gliding with an Elytra equipped.
	elytraBoostEnabled = true
	#Multiplier for Jetpack fuel consumption while Elytra boosting.
	#Range: 1 ~ 10
	elytraBoostMultiplier = 4
	#Apply mining speed penalty when flying with the Jetpack.
	jetpackMiningPenalty = true

	#Magnet Upgrade
	[backpack.magnet_upgrade]
		#The range (in blocks) around the backpack within which the Magnet Upgrade will pull items.
		#Range: 2 ~ 16
		backpackMagnetRange = 5

	#Ore Mining Upgrade
	[backpack.ore_mining_upgrade]
		#Limits the Ore Mining Upgrade to mine ores only. Disable to allow all blocks (up to 64).
		mineOresOnly = true

	#Flight Upgrade
	[backpack.flight_upgrade]
		#Allow the use of the flight upgrade over the void in The End dimension.
		jetpackAllowVoidFlight = false

#Storage Box
[storage_box]
	#The number of ticks before Storage Boxes update their block count and block states. Higher value = better performance.
	storageBoxUpdateTime = 20

#Storage Network
[storage_network]
	#When all existing boxes with matching filters are full, allow the Storage Network to insert into empty boxes instead.
	allowInsertIntoEmptyBoxes = true
	#The maximum number of blocks the storage network will search from the controller to find connected components.
	#Range: 8 ~ 64
	simpleStorageNetworkRange = 32
	#The number of ticks between each update check for controllers and interfaces to refresh their connection to the storage network.
	simpleStorageNetworkUpdateTime = 20

