#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 24 12:05:03 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryUnbound_r5.5.1 + EuphoriaPatches_1.6.5
enableShaders=false
